### ISSUE TITLE
Issue with imports

### ISSUE THREAD

**Issue by nr1brolyfan** [block65/webcrypto-web-push#3]
It seems like its impossible to import the package
```ts
import {
	type PushSubscription,
	type PushMessage,
	type VapidKeys,
	buildPushPayload
} from '@block65/webcrypto-web-push';
```
![image](https://github.com/block65/webcrypto-web-push/assets/88940768/620c2baa-b278-4927-95fc-e25905ada5c4)

**Comment by nr1brolyfan** [comment]
So it seems like the import works despite the error in vscode, so it's not a big issue
![image](https://github.com/block65/webcrypto-web-push/assets/88940768/31b7f611-c123-4499-b86f-e2c1aa2edaf7)

**Comment by maxholman** [comment]
The error you encountered is likely due to TypeScript not reading the `exports`  field in this package. 

As this package is ESM only, you will need to set `moduleResolution` to be either `Node16`, `NodeNext`, or `bundler` in your tsconfig.json to correctly resolve the `exports`.

I will make this clearer in the README.

Thanks for the report!
